os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -project /Users/shreyapallan/Desktop/"iOS Practice Apps"/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO